//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGO.Integration.Infra.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewGO.Integration.Infra.Messages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado no sistema.
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar inserir o registro.
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar atualizar o registro.
        /// </summary>
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar excluir o registro.
        /// </summary>
        internal static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar obter o registro.
        /// </summary>
        internal static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar consultar todos os registros.
        /// </summary>
        internal static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar consultar os registros paginados.
        /// </summary>
        internal static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar processar a alteração da senha.
        /// </summary>
        internal static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar processar o fluxo de esquecimento de senha.
        /// </summary>
        internal static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar processar o envio de mensagens.
        /// </summary>
        internal static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar processar o envio de mensagens.
        /// </summary>
        internal static string E0011 {
            get {
                return ResourceManager.GetString("E0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao entar efetuar o login.
        /// </summary>
        internal static string E0012 {
            get {
                return ResourceManager.GetString("E0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao entar efetuar o login por token.
        /// </summary>
        internal static string E0013 {
            get {
                return ResourceManager.GetString("E0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu erro ao tentar {0}..
        /// </summary>
        internal static string E0014 {
            get {
                return ResourceManager.GetString("E0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado.
        /// </summary>
        internal static string N0001 {
            get {
                return ResourceManager.GetString("N0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o registro.
        /// </summary>
        internal static string N0002 {
            get {
                return ResourceManager.GetString("N0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado.
        /// </summary>
        internal static string N0003 {
            get {
                return ResourceManager.GetString("N0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ser informado..
        /// </summary>
        internal static string V0001 {
            get {
                return ResourceManager.GetString("V0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser informada..
        /// </summary>
        internal static string V0002 {
            get {
                return ResourceManager.GetString("V0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} é inválido..
        /// </summary>
        internal static string V0003 {
            get {
                return ResourceManager.GetString("V0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} é inválida..
        /// </summary>
        internal static string V0004 {
            get {
                return ResourceManager.GetString("V0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ter ao menos 1 item..
        /// </summary>
        internal static string V0005 {
            get {
                return ResourceManager.GetString("V0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ter ao menos 1 item..
        /// </summary>
        internal static string V0006 {
            get {
                return ResourceManager.GetString("V0006", resourceCulture);
            }
        }
    }
}
